services:
  mariadb:
    image: my_mariadb_image
    container_name: my_mariadb_container
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    expose:
      - "3306"
    networks:
      - inception_frontend
    healthcheck:
      test: ["CMD", "sh", "-c", "if test -f /tmp/mariadb_ready && mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD --silent; then exit 0; else exit 1; fi"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

  wordpress:
    image: my_wordpress_image
    container_name: my_wordpress_container
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_volume:/var/www/html/
    env_file: .env
    expose:
      - "9000"
    networks:
      # - inception_backend
      - inception_frontend
    # healthcheck:
    #   test: ["CMD", "-f /tmp/health_check.php | grep 'healthy' || exit 1"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 40s
    restart: unless-stopped

  nginx:
    image: my_nginx_image
    container_name: my_nginx_container
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
      # wordpress:
        # condition: service_healthy
    volumes:
      - wordpress_volume:/var/www/html/
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception_frontend
    # healthcheck:
    #   test: 'curl -kfs -SL https://127.0.0.1:9000'
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 15s
    restart: unless-stopped

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/sydauria/data/mariadb/
  wordpress_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/sydauria/data/wordpress

networks:
  # inception_backend:
  #   driver: bridge
  inception_frontend:
    driver: bridge
