services:
  mariadb:
    image: my_mariadb_image
    container_name: my_mariadb_container
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    expose:
      - 3306
    networks:
      - inception_backend
    # healthcheck:
    #   test: ["CMD-SHELL", "mysqladmin ping --silent"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 2
    #   start_period: 15s
    restart: unless-stopped

  # wordpress:
  #   image: my_wordpress_image
  #   container_name: my_wordpress_container
  #   build:
  #     context: ./requirements/wordpress
  #     dockerfile: Dockerfile
  #   depends_on:
  #     mariadb:
  #       condition: service_healthy
  #   volumes:
  #     - wordpress_volume:/var/www/html/
  #   env_file: .env
  #   expose:
  #     - 9000
  #   networks:
  #     - inception_backend
  #     - inception_frontend
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s
  #   restart: unless-stopped

  # nginx:
  #   image: my_nginx_image
  #   container_name: my_nginx_container
  #   build:
  #     context: ./requirements/nginx
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - wordpress
  #   volumes:
  #     - wordpress_volume:/var/www/html/
  #   env_file: .env
  #   ports:
  #     - 443:443
  #   networks:
  #     - inception_frontend
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 10
  #     start_period: 15s
  #   restart: unless-stopped

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./data/mariadb
  # wordpress_volume:
  #   driver: local
  #   driver_opts:
  #     type: 'none'
  #     o: 'bind'
  #     device: ./data/wordpress

networks:
  inception_backend:
    driver: bridge
  inception_frontend:
    driver: bridge
